# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Update the system and install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget unzip libnss3 libgconf-2-4 chromium-driver postgresql-client gnupg && \
    rm -rf /var/lib/apt/lists/*

# Install Chrome WebDriver
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y chromium && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script into the container
COPY sreality.py .

# Specify the command to run the Python script
CMD ["python", "sreality.py"]
